export const ARMOR_SLOTS = {
		Head: 'Head',
		Torso: 'Torso',
		Arms: 'Arms',
		Hands: 'Hands',
		Legs: 'Legs',
		Feet: 'Feet',
	},
	BODY_PARTS = [
		// ['Cranium', true, 2, [], ARMOR_SLOTS.Head],
		// ['Face', true, 1, [], ARMOR_SLOTS.Head],
		// ['Neck', true, 1, [], ARMOR_SLOTS.Head],
		['Chest', true, 4, [], ARMOR_SLOTS.Torso],
		// ['Abdomen', false, 8, ['Left Thigh', 'Right Thigh'], ARMOR_SLOTS.Torso],
		// ['Left Shoulder', false, 8, ['Left Arm'], ARMOR_SLOTS.Arms],
		// ['Left Arm', false, 8, ['Left Hand'], ARMOR_SLOTS.Arms],
		// ['Left Hand', false, 5, [], ARMOR_SLOTS.Arms],
		// ['Right Shoulder', false, 8, ['Right Arm'], ARMOR_SLOTS.Arms],
		// ['Right Arm', false, 8, ['Right Hand'], ARMOR_SLOTS.Arms],
		// ['Right Hand', false, 5, [], ARMOR_SLOTS.Arms],
		// ['Left Hip', false, 8, ['Left Crus'], ARMOR_SLOTS.Legs],
		// ['Left Leg', false, 8, ['Left Foot'], ARMOR_SLOTS.Legs],
		// ['Left Foot', false, 5, [], ARMOR_SLOTS.Feet],
		// ['Right Hip', false, 8, ['Right Crus'], ARMOR_SLOTS.Legs],
		// ['Right Leg', false, 8, ['Right Foot'], ARMOR_SLOTS.Legs],
		// ['Right Foot', false, 5, [], ARMOR_SLOTS.Feet],
	];
